apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hello-api
  namespace: hello-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-api
  minReplicas: 2
  maxReplicas: 5
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 400
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70